services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./assets:/srv/app/assets
      - ./src:/srv/app/src
      - ./Cargo.lock:/srv/app/Cargo.lock
      - ./Cargo.toml:/srv/app/Cargo.toml
      - ./diesel.toml:/srv/app/diesel.toml
      - ./Dioxus.toml:/srv/app/Dioxus.toml
    restart: always
    ports: [ "8000:8000" ]
